language: php
php:
  - "5.4"
  - "5.5"

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tor
  - sudo service tor stop
  - tor -f tests/torrc &
  - sleep 10
  - composer install
